import ICAL from 'ical.js';
import { toInstant, instantOf, frameOf, documentZone } from './tools/shared/ical-dates.js';

/**
 * Which occurrences of a recurring event touch a time range — the one answer
 * free/busy, calendar_query, list_events and the event display all read.
 *
 * A CalDAV server answers a time-range query with the whole calendar object
 * of a recurring series, not with the occurrences inside the range, so the
 * series is expanded here. Each occurrence is taken as it now stands: an
 * override with the same RECURRENCE-ID replaces it (its own time, STATUS,
 * TRANSP, title), a RANGE=THISANDFUTURE override moves every later one, an
 * EXDATE removes it. An override whose RECURRENCE-ID is no occurrence of the
 * series — EXDATEd, or never generated by the rule — is ignored, as RFC 5545
 * 3.8.4.4 expects of a reader.
 *
 * "Touches the range" is RFC 4791 9.9's time-range test, half-open: the
 * occurrence starts before the range ends and ends after it starts; one
 * without duration touches it when it starts in [start, end). All instants
 * are read as toInstant reads them — a floating time on the host clock, a
 * date as its UTC day.
 */

// Server-supplied data must not be able to stall a query, so the steps one
// call may take through a series — every walk of it together — are capped.
// A call that runs out says so (`truncated`), and what it returns is then
// incomplete but not wrong (see seriesOccurrences).
const MAX_RECURRENCE_STEPS = 25000;

/**
 * Milliseconds a wall-clock time can sit away from the same digits read as
 * UTC: zone offsets run from UTC-12 to UTC+14. For bounds that compare a
 * floating time read in the host's zone with an instant (calendar_query's
 * sort key).
 */
export const ZONE_SLACK_MS = 26 * 3600 * 1000;

const DAY_MS = 86400 * 1000;

// Every comparison below is between instants or between wall clocks of the
// one frame of DTSTART. Only a duration or a THISANDFUTURE move added on the
// wall clock can differ from its length in instants, by a DST change: this
// much margin covers it.
const DST_SLACK_MS = 3 * 3600 * 1000;

/**
 * RFC 4791 9.9: does [start, end) touch [range.start, range.end)?
 *
 * @param {number} start - ms
 * @param {number} end - ms; equal to start for an occurrence without duration
 * @param {{start: number, end: number}} range - ms
 */
export function touchesRange(start, end, range) {
  return start < range.end && (end > range.start || start >= range.start);
}

/**
 * The instants an occurrence (getOccurrenceDetails' shape) spans, in ms.
 *
 * @param {{startDate: ICAL.Time, endDate?: ICAL.Time}} occurrence
 * @returns {{start: number, end: number}}
 */
export function spanOf({ startDate, endDate }) {
  const start = toInstant(startDate);
  const end = endDate ? toInstant(endDate) : start;
  return { start, end: Math.max(start, end) };
}

/**
 * A series master with its overrides related, ready to expand.
 *
 * Each override's RECURRENCE-ID is first rewritten in the master's DTSTART
 * form (RFC 5545 3.8.4.4: same value type, and it names the instant of the
 * occurrence it overrides). ical.js matches an override to an occurrence by
 * the text of its RECURRENCE-ID, so `…T080000Z` never matched the occurrence
 * `…T100000` in Europe/Berlin it names, and a THISANDFUTURE override's shift
 * was computed by copying zones rather than converting. The rewrite happens
 * on the parsed component, in memory only.
 *
 * EXDATEs are rewritten the same way: ical.js matches them by comparing
 * times, which reads a floating time as UTC, where the RECURRENCE-IDs above
 * and every instant here read it on the host clock.
 *
 * RANGE=THISANDFUTURE is applied here (occurrenceAt), not by ical.js, which
 * applies such an override even when its RECURRENCE-ID is no occurrence.
 *
 * @param {ICAL.Component} master
 * @param {ICAL.Component[]} overrides - its RECURRENCE-ID siblings
 * @returns {{event: ICAL.Event, futures: Object[], plan: Object|null}}
 */
export function relateSeries(master, overrides) {
  // an empty list: without one, ical.js relates every sibling with a
  // RECURRENCE-ID itself, before it is aligned
  const event = new ICAL.Event(master, { exceptions: [] });
  alignExdates(master);
  const futures = [];
  // each override also by the instant its RECURRENCE-ID named as written: at
  // a DST fold the aligned wall clock is ambiguous, the instant is not
  const byInstant = new Map();
  // keys whose aligned wall clock is not the instant they named (a DST fold)
  const folded = new Set();
  for (const override of overrides) {
    const named = namedInstant(override, master);
    alignRecurrenceId(override, master);
    const related = new ICAL.Event(override);
    if (!related.recurrenceId) continue;
    event.relateException(related);
    const key = related.recurrenceId.toString();
    const at = Number.isFinite(named) ? named : toInstant(related.recurrenceId);
    byInstant.set(at, key);
    if (toInstant(related.recurrenceId) !== at) folded.add(key);
    if (related.modifiesFuture()) {
      futures.push({
        key, exception: related, at, wall: wallOf(related.recurrenceId),
      });
    }
  }
  event.rangeExceptions = [];
  return {
    event,
    byInstant,
    folded,
    // a later override with the same RECURRENCE-ID replaced an earlier one
    futures: futures.filter((f) => event.exceptions[f.key] === f.exception).sort((a, b) => a.at - b.at),
    plan: shiftPlan(event),
  };
}

/**
 * The instant a RECURRENCE-ID names as written — only where it is a
 * date-time naming a timed series; a date against a date-time (or the other
 * way round) names an occurrence only through alignedValue.
 */
function namedInstant(override, master) {
  const property = override.getFirstProperty('recurrence-id');
  const dtstart = master.getFirstProperty('dtstart');
  if (!property || !dtstart) return null;
  if (property.getFirstValue().isDate || dtstart.getFirstValue().isDate) return null;
  return orNull(() => instantOf(property));
}

function alignRecurrenceId(override, master) {
  const property = override.getFirstProperty('recurrence-id');
  const dtstart = master.getFirstProperty('dtstart');
  if (!property || !dtstart || frameOf(property) === frameOf(dtstart)) return;
  const aligned = alignedValue(property, property.getFirstValue(), dtstart, 'as-written');
  if (!aligned) return;
  property.setValue(aligned);
  setFrameOf(property, dtstart);
}

function alignExdates(master) {
  const dtstart = master.getFirstProperty('dtstart');
  if (!dtstart) return;
  for (const property of master.getAllProperties('exdate')) {
    if (frameOf(property) === frameOf(dtstart)) continue;
    // a date excluding a timed occurrence: ical.js matches it by its day
    if (property.getFirstValue()?.isDate && !dtstart.getFirstValue().isDate) continue;
    const values = property.getValues().map((value) => alignedValue(property, value, dtstart, 'utc-day'));
    if (values.some((value) => !value)) continue;
    property.setValues(values);
    setFrameOf(property, dtstart);
  }
}

/**
 * A RECURRENCE-ID or EXDATE value written in the frame of DTSTART, naming
 * the same occurrence:
 *  - a date for a timed series: the series' time of day on that date
 *  - a date-time for an all-day series: for a RECURRENCE-ID the date as
 *    written (its own wall date), for an EXDATE the UTC day of its instant
 *  - otherwise the same instant (a floating time read on the host clock)
 */
function alignedValue(property, value, dtstart, dateOfTimed) {
  const start = dtstart.getFirstValue();
  if (value.isDate && !start.isDate) {
    const aligned = start.clone();
    aligned.year = value.year;
    aligned.month = value.month;
    aligned.day = value.day;
    return aligned;
  }
  if (start.isDate && !value.isDate && dateOfTimed === 'as-written') {
    return new ICAL.Time({ year: value.year, month: value.month, day: value.day, isDate: true });
  }
  let instant;
  try {
    instant = instantOf(property, value);
  } catch {
    return null;
  }
  return Number.isFinite(instant) ? timeLike(instant, dtstart) : null;
}

function setFrameOf(property, dtstart) {
  const tzid = dtstart.getParameter('tzid');
  if (tzid) property.setParameter('tzid', tzid);
  else property.removeParameter('tzid');
}

/**
 * An instant written in the frame of a date or date-time property: a date as
 * its UTC day, UTC, the property's VTIMEZONE, or — floating, or a TZID
 * without its VTIMEZONE — the host's wall clock, as toInstant reads those.
 */
function timeLike(instant, property, value = property.getFirstValue()) {
  const date = new Date(instant);
  if (value.isDate) {
    return new ICAL.Time({ year: date.getUTCFullYear(), month: date.getUTCMonth() + 1, day: date.getUTCDate(), isDate: true });
  }
  const frame = frameOf(property);
  if (frame === 'utc') return ICAL.Time.fromJSDate(date, true);
  const zone = documentZone(property);
  if (zone) return ICAL.Time.fromJSDate(date, true).convertToZone(zone);
  return new ICAL.Time({
    year: date.getFullYear(), month: date.getMonth() + 1, day: date.getDate(),
    hour: date.getHours(), minute: date.getMinutes(), second: date.getSeconds(),
  });
}

/**
 * The occurrence with recurrence id `id`, after its overrides: an exact
 * override if there is one, else the latest valid THISANDFUTURE override at
 * or before it, else the series itself. `futures` are the THISANDFUTURE
 * overrides that are occurrences (see validate), sorted.
 *
 * A THISANDFUTURE override moves later occurrences by its own move, read as
 * wall-clock time in its DTSTART's frame (so 10:00 -> 11:00 stays 11:00
 * across a DST change), and gives them its duration and properties.
 *
 * @returns {{recurrenceId: ICAL.Time, startDate: ICAL.Time, endDate: ICAL.Time, item: ICAL.Event}}
 */
function occurrenceAt(series, id, futures) {
  const { event } = series;
  const key = exceptionKey(series, id);
  if (key) {
    const item = event.exceptions[key];
    return { recurrenceId: id, startDate: item.startDate, endDate: item.endDate, item };
  }
  const end = id.clone();
  end.addDuration(event.duration);
  const details = { recurrenceId: id, startDate: id, endDate: end, item: event };
  if (futures.length === 0) return details;

  const at = toInstant(id);
  let future = null;
  for (const candidate of futures) {
    if (candidate.at > at) break;
    future = candidate;
  }
  if (!future) return details;

  const exception = future.exception;
  const startProperty = exception.component.getFirstProperty('dtstart');
  if (!startProperty) return details;
  const move = exception.startDate.subtractDate(timeLike(future.at, startProperty));
  const startDate = timeLike(at, startProperty);
  startDate.addDuration(move);
  const endDate = startDate.clone();
  endDate.addDuration(exception.duration);
  return { recurrenceId: id, startDate, endDate, item: exception };
}

/** The key of the exact override of occurrence `id`, if any: by text, else by instant */
function exceptionKey({ event, byInstant }, id) {
  const local = id.toString();
  if (local in event.exceptions) return local;
  const key = byInstant.get(toInstant(id));
  return key && event.exceptions[key] ? key : null;
}

function orNull(compute) {
  try {
    return compute();
  } catch {
    return null;
  }
}

/**
 * The occurrences of a recurring series that touch `range` and that `filter`
 * takes, each as it now stands (occurrenceAt).
 *
 * Without walking the whole series:
 *
 *  - Overrides with their own RECURRENCE-ID are a finite list, each with its
 *    own time. Those that touch the range are collected first, from anywhere
 *    in the series — that is how one moved in from years away is found.
 *  - Whether they, and any THISANDFUTURE overrides, are occurrences at all
 *    is checked in one pass over their sorted RECURRENCE-IDs (validate),
 *    a few steps each where the rule allows (shiftPlan).
 *  - Every other occurrence sits at its recurrence id, moved at most by a
 *    valid THISANDFUTURE override and lasting at most the longest duration
 *    in the series. So only the recurrence ids in the range, widened by that
 *    move and duration, are walked — from the period that holds the range
 *    where the rule allows (shiftPlan), else from DTSTART.
 *  - All walks of one call share one step budget.
 *
 * @param {ReturnType<typeof relateSeries>} series
 * @param {{start: number, end: number}} range - ms
 * @param {Object} [options]
 * @param {((occurrence: Object) => boolean)|null} [options.filter] - beyond
 *   touching the range (a search, blocking time)
 * @param {boolean} [options.first] - only the earliest is wanted: the walk
 *   stops once no later recurrence id can start before it
 * @returns {{occurrences: Object[], truncated: boolean}} sorted by start,
 *   then recurrence id; truncated when the step budget ran out. Then some
 *   occurrences may be missing, but none is wrong: an override that could
 *   not be checked is left out, and so is every occurrence a THISANDFUTURE
 *   override that could not be checked might move.
 */
export function seriesOccurrences(series, range, { filter = null, first = false } = {}) {
  const accept = (occurrence) => {
    const { start, end } = spanOf(occurrence);
    return touchesRange(start, end, range) && (!filter || filter(occurrence));
  };
  const budget = { left: MAX_RECURRENCE_STEPS, exhausted: false };

  const overrides = overridesInRange(series, accept);
  const checked = validate(series, [...overrides, ...series.futures], budget);
  const futures = series.futures.filter((f) => checked.ids.has(f.key));
  const found = overrides
    .filter((o) => checked.ids.has(o.key))
    .map((o) => occurrenceAt(series, checked.ids.get(o.key), futures));

  // an occurrence at or after a THISANDFUTURE override nobody could check
  // may be moved by it: not reported, rather than reported wrong
  const unknown = series.futures.find((f) => f.wall + DST_SLACK_MS >= checked.decidedBefore);
  const walked = walkRange(series, range, futures, accept, {
    best: first ? earliest(found) : null,
    before: unknown ? unknown.wall : Infinity,
    budget,
  });
  found.push(...walked.found);
  const truncated = budget.exhausted || Boolean(unknown);
  if (truncated) {
    console.error(`Recurrence expansion gave up after ${MAX_RECURRENCE_STEPS} steps`);
  }
  found.sort(byStart);
  return { occurrences: first ? found.slice(0, 1) : found, truncated };
}

/** The exact overrides whose own time `accept` takes: {key, wall} */
function overridesInRange({ event }, accept) {
  return Object.entries(event.exceptions)
    .filter(([, exception]) => accept(event.getOccurrenceDetails(exception.recurrenceId)))
    .map(([key, exception]) => ({ key, wall: wallOf(exception.recurrenceId) }));
}

function earliest(occurrences) {
  return Math.min(Infinity, ...occurrences.map((o) => spanOf(o).start));
}

/**
 * Walk the recurrence ids that can still yield an occurrence touching the
 * range, skipping exact overrides (judged by overridesInRange). With `best`
 * (first mode), stop once a later id cannot start before it; stop at the
 * wall clock `before` (see seriesOccurrences).
 */
function walkRange(series, range, futures, accept, { best, before, budget }) {
  const { event } = series;
  const { lead, trail, minMove } = reach(series, futures);
  const from = range.start - lead;
  const to = range.end + trail;
  const dtstart = event.component.getFirstProperty('dtstart');
  const walk = walkFrom(series, wallOf(timeLike(from, dtstart)) - DST_SLACK_MS, budget);
  const found = [];
  let bound = best ?? Infinity;
  for (let id = walk.next(); id; id = walk.next()) {
    if (wallOf(id) >= before) break;
    const at = toInstant(id);
    if (at > to) break;
    if (at < from) continue;
    if (best !== null && at + minMove - DST_SLACK_MS > bound) break;
    if (exceptionKey(series, id)) continue;
    const occurrence = occurrenceAt(series, id, futures);
    if (accept(occurrence)) {
      found.push(occurrence);
      bound = Math.min(bound, spanOf(occurrence).start);
    }
  }
  return { found };
}

/**
 * How far an occurrence can sit from its recurrence id, in ms: `lead` back
 * (it may start before its id and run on into the range), `trail` forward,
 * and the most negative move a valid THISANDFUTURE override applies.
 */
function reach({ event }, futures) {
  const moves = [0];
  const durations = [durationOf(event)];
  for (const { exception, at } of futures) {
    moves.push(toInstant(exception.startDate) - at);
    durations.push(durationOf(exception));
  }
  const minMove = Math.min(...moves);
  return {
    lead: Math.max(...moves) + Math.max(0, ...durations) + DST_SLACK_MS,
    trail: -minMove + DST_SLACK_MS,
    minMove,
  };
}

function durationOf(event) {
  try {
    const ms = event.duration.toSeconds() * 1000;
    return Number.isFinite(ms) ? ms : 0;
  } catch {
    return 0;
  }
}

/**
 * Which of the given overrides are occurrences of the series — does the
 * rule, less its EXDATEs, yield their RECURRENCE-ID? One pass over the ids
 * in order. Where the rule can be shifted (shiftPlan), each id ahead of the
 * pass gets a walk from the start of the period it lies in, so checking an
 * override costs a few steps however far it is from DTSTART; otherwise one
 * walk runs on from DTSTART. All of it from the caller's step budget.
 *
 * Compares wall clocks in DTSTART's frame: the RECURRENCE-IDs are aligned to
 * it (relateSeries) and the walk yields it.
 *
 * @param {Object[]} targets - {key, wall}
 * @returns {{ids: Map<string, ICAL.Time>, decidedBefore: number}} each valid
 *   key with its id as the rule yields it; every target before the wall
 *   clock `decidedBefore` was decided (Infinity: all of them)
 */
function validate(series, targets, budget) {
  const ids = new Map();
  const pending = [...new Map(targets.map((t) => [t.key, t])).values()].sort((a, b) => a.wall - b.wall);
  const keys = new Set(pending.map((t) => t.key));
  let walk = null;
  let position = -Infinity;
  for (let i = 0; i < pending.length;) {
    const target = pending[i];
    // aligned at a DST fold, a wall clock may sit an hour off its occurrence
    const slack = series.folded.has(target.key) ? DST_SLACK_MS : 0;
    if (target.wall + slack < position) {
      i++;
      continue;
    }
    if (!walk || (series.plan && periodStart(series, target.wall - slack) > position)) {
      walk = walkFrom(series, target.wall - slack, budget);
    }
    const id = walk.next();
    if (!id) {
      // the series ended: no later id is an occurrence; or the budget did
      return { ids, decidedBefore: budget.exhausted ? target.wall - slack : Infinity };
    }
    position = wallOf(id);
    const key = exceptionKey(series, id);
    if (key && keys.has(key)) ids.set(key, id);
  }
  return { ids, decidedBefore: Infinity };
}

/**
 * The recurrence ids of a series in order, from the start of the period
 * that holds the wall clock `wall` (DTSTART's frame) where shiftPlan allows,
 * else from DTSTART. ical.js always yields the start it is given, so a
 * shifted start the rule would not generate is dropped. next() returns null
 * at the end of the series or when the budget is spent.
 */
function walkFrom(series, wall, budget) {
  const { event, plan } = series;
  let dtstart = event.startDate;
  let skipFirst = false;
  const periods = plan ? Math.floor((wall - wallOf(dtstart)) / plan.periodMs) : 0;
  if (periods > 0) {
    dtstart = shifted(series, periods);
    skipFirst = !generates(plan.rule, dtstart);
  }
  const expansion = new ICAL.RecurExpansion({ component: event.component, dtstart });
  return {
    next() {
      for (;;) {
        if (budget.left <= 0) {
          budget.exhausted = true;
          return null;
        }
        budget.left--;
        const id = expansion.next();
        if (!id || (plan?.last && id.compare(plan.last) > 0)) return null;
        if (skipFirst) {
          skipFirst = false;
          if (id.compare(dtstart) === 0) continue;
        }
        return id;
      }
    },
  };
}

/** The wall clock where the period holding `wall` begins */
function periodStart(series, wall) {
  const start = wallOf(series.event.startDate);
  const periods = Math.floor((wall - start) / series.plan.periodMs);
  return periods > 0 ? wallOf(shifted(series, periods)) : start;
}

function shifted({ event, plan }, periods) {
  const time = event.startDate.clone();
  const ms = periods * plan.periodMs;
  if (ms % DAY_MS === 0) time.adjust(ms / DAY_MS, 0, 0, 0);
  else time.adjust(0, 0, 0, ms / 1000);
  return time;
}

const WEEKDAYS = ['SU', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA'];

/**
 * Would the rule generate this start of a period? For the rules shiftPlan
 * admits, that is: each BY part present holds its field (BYDAY its weekday).
 * An absent part defaults to DTSTART's, which a whole number of periods
 * later is unchanged.
 */
function generates(rule, time) {
  const holds = {
    BYDAY: WEEKDAYS[time.dayOfWeek() - 1],
    BYMONTH: time.month,
    BYHOUR: time.hour,
    BYMINUTE: time.minute,
    BYSECOND: time.second,
  };
  return Object.entries(holds).every(([part, value]) => {
    const allowed = rule.parts?.[part];
    return !allowed || allowed.map(String).includes(String(value));
  });
}

/** Wall-clock ms of a time's own fields (a date at midnight) */
function wallOf(time) {
  return Date.UTC(time.year, time.month - 1, time.day,
    time.isDate ? 0 : time.hour, time.isDate ? 0 : time.minute, time.isDate ? 0 : time.second);
}

// Rule parts that keep a series periodic in its INTERVAL: the candidates are
// the same in every period, so the expansion can start a whole number of
// periods later without changing which occurrences it yields.
const PERIODIC_PARTS = new Set(['BYDAY', 'BYMONTH', 'BYHOUR', 'BYMINUTE', 'BYSECOND', 'WKST']);
const UNIT_SECONDS = { SECONDLY: 1, MINUTELY: 60, HOURLY: 3600, DAILY: 86400, WEEKLY: 604800 };
const TIME_PARTS = { BYHOUR: 3600, BYMINUTE: 60, BYSECOND: 1 };

/**
 * Whether, and in which steps, a walk may start later than DTSTART.
 *
 * Walking from DTSTART costs one step per occurrence since the series began:
 * a daily series from 2020 takes ~2400 steps to reach October 2026, an
 * every-minute one never gets there. For a SECONDLY to WEEKLY rule whose BY
 * parts are BYDAY (without an ordinal), BYMONTH, WKST, or a BYHOUR, BYMINUTE
 * or BYSECOND finer than the frequency (one that expands it, as BYHOUR does
 * a DAILY rule), the occurrences repeat every period: ical.js steps the period on
 * the wall clock, and these parts test fields of the wall clock. So a start
 * moved by whole periods (`periodMs`, on DTSTART's wall clock) yields the
 * same occurrences from there on; EXDATEs and overrides are absolute and
 * still apply. With COUNT, only a rule without BY parts qualifies: its last
 * occurrence (`last`) is then DTSTART plus COUNT-1 periods, and the walk
 * stops there. Anything else — RDATE, several RRULEs, MONTHLY, YEARLY, other
 * BY parts — is walked from DTSTART; monthly and yearly series have few
 * occurrences.
 *
 * @returns {{periodMs: number, last: ICAL.Time|null, rule: ICAL.Recur}|null}
 */
function shiftPlan(event) {
  const component = event.component;
  const rules = component.getAllProperties('rrule');
  if (rules.length !== 1 || component.hasProperty('rdate')) return null;
  const rule = rules[0].getFirstValue();
  const unit = UNIT_SECONDS[rule.freq];
  if (!unit) return null;
  const parts = Object.keys(rule.parts ?? {});
  if (parts.some((part) => !PERIODIC_PARTS.has(part))) return null;
  if ((rule.parts.BYDAY ?? []).some((day) => !WEEKDAYS.includes(String(day)))) return null;
  // a time-of-day part that limits the rule rather than expanding it
  // (BYHOUR on HOURLY, say): ical.js does not step those on a fixed grid
  if (parts.some((part) => TIME_PARTS[part] && TIME_PARTS[part] >= unit)) return null;

  const period = (rule.interval || 1) * unit;
  if (event.startDate.isDate && period % 86400 !== 0) return null;
  let last = null;
  if (rule.count) {
    if (parts.some((part) => part !== 'WKST')) return null;
    last = event.startDate.clone();
    const span = (rule.count - 1) * period;
    if (span % 86400 === 0) last.adjust(span / 86400, 0, 0, 0);
    else last.adjust(0, 0, 0, span);
  }
  return { periodMs: period * 1000, last, rule };
}

function byStart(a, b) {
  return spanOf(a).start - spanOf(b).start || toInstant(a.recurrenceId) - toInstant(b.recurrenceId);
}
