import ICAL from 'ical.js';
import { toInstant, instantOf, frameOf, documentZone } from './tools/shared/ical-dates.js';

/**
 * Which occurrences of a recurring event touch a time range — the one answer
 * free/busy, calendar_query, list_events and the event display all read.
 *
 * A CalDAV server answers a time-range query with the whole calendar object
 * of a recurring series, not with the occurrences inside the range, so the
 * series is expanded here. Each occurrence is taken as it now stands: an
 * override with the same RECURRENCE-ID replaces it (its own time, STATUS,
 * TRANSP, title), a RANGE=THISANDFUTURE override moves every later one, an
 * EXDATE removes it. An override whose RECURRENCE-ID is no occurrence of the
 * series — EXDATEd, or never generated by the rule — is ignored, as RFC 5545
 * 3.8.4.4 expects of a reader.
 *
 * "Touches the range" is RFC 4791 9.9's time-range test, half-open: the
 * occurrence starts before the range ends and ends after it starts; one
 * without duration touches it when it starts in [start, end). All instants
 * are read as toInstant reads them — a floating time on the host clock, a
 * date as its UTC day.
 */

// The cost of expansion scales with the distance from where the walk starts
// to the range, so the walk is capped: server-supplied data must not be able
// to stall the loop. A walk that hits the cap says so (`truncated`).
const MAX_RECURRENCE_ITERATIONS = 10000;

/**
 * Milliseconds a wall-clock time can sit away from the same digits read as
 * UTC: zone offsets run from UTC-12 to UTC+14. Every window computed from
 * recurrence ids is widened by this much and the exact test decides.
 */
export const ZONE_SLACK_MS = 26 * 3600 * 1000;

const DAY_MS = 86400 * 1000;

/**
 * RFC 4791 9.9: does [start, end) touch [range.start, range.end)?
 *
 * @param {number} start - ms
 * @param {number} end - ms; equal to start for an occurrence without duration
 * @param {{start: number, end: number}} range - ms
 */
export function touchesRange(start, end, range) {
  return start < range.end && (end > range.start || start >= range.start);
}

/**
 * The instants an occurrence (getOccurrenceDetails' shape) spans, in ms.
 *
 * @param {{startDate: ICAL.Time, endDate?: ICAL.Time}} occurrence
 * @returns {{start: number, end: number}}
 */
export function spanOf({ startDate, endDate }) {
  const start = toInstant(startDate);
  const end = endDate ? toInstant(endDate) : start;
  return { start, end: Math.max(start, end) };
}

/**
 * A series master with its overrides related, ready to expand.
 *
 * Each override's RECURRENCE-ID is first rewritten in the master's DTSTART
 * form (RFC 5545 3.8.4.4: same value type, and it names the instant of the
 * occurrence it overrides). ical.js matches an override to an occurrence by
 * the text of its RECURRENCE-ID, so `…T080000Z` never matched the occurrence
 * `…T100000` in Europe/Berlin it names, and a THISANDFUTURE override's shift
 * was computed by copying zones rather than converting. The rewrite happens
 * on the parsed component, in memory only.
 *
 * RANGE=THISANDFUTURE is applied here (occurrenceAt), not by ical.js, which
 * applies such an override even when its RECURRENCE-ID is no occurrence.
 *
 * @param {ICAL.Component} master
 * @param {ICAL.Component[]} overrides - its RECURRENCE-ID siblings
 * @returns {{event: ICAL.Event, futures: Object[], plan: Object|null}}
 */
export function relateSeries(master, overrides) {
  // an empty list: without one, ical.js relates every sibling with a
  // RECURRENCE-ID itself, before it is aligned
  const event = new ICAL.Event(master, { exceptions: [] });
  const futures = [];
  for (const override of overrides) {
    alignRecurrenceId(override, master);
    const related = new ICAL.Event(override);
    if (!related.recurrenceId) continue;
    event.relateException(related);
    if (related.modifiesFuture()) {
      futures.push({ key: related.recurrenceId.toString(), exception: related, at: toInstant(related.recurrenceId) });
    }
  }
  event.rangeExceptions = [];
  return {
    event,
    // a later override with the same RECURRENCE-ID replaced an earlier one
    futures: futures.filter((f) => event.exceptions[f.key] === f.exception).sort((a, b) => a.at - b.at),
    plan: shiftPlan(event),
  };
}

function alignRecurrenceId(override, master) {
  const property = override.getFirstProperty('recurrence-id');
  const dtstart = master.getFirstProperty('dtstart');
  if (!property || !dtstart || frameOf(property) === frameOf(dtstart)) return;
  const value = property.getFirstValue();
  const start = dtstart.getFirstValue();

  let aligned;
  if (value.isDate && !start.isDate) {
    // a date naming a timed occurrence: the series' time on that day
    aligned = start.clone();
    aligned.year = value.year;
    aligned.month = value.month;
    aligned.day = value.day;
  } else {
    let instant;
    try {
      instant = instantOf(property);
    } catch {
      return;
    }
    if (!Number.isFinite(instant)) return;
    aligned = timeLike(instant, dtstart);
  }
  property.setValue(aligned);
  const tzid = dtstart.getParameter('tzid');
  if (tzid) property.setParameter('tzid', tzid);
  else property.removeParameter('tzid');
}

/**
 * An instant written in the frame of a date or date-time property: a date as
 * its UTC day, UTC, the property's VTIMEZONE, or — floating, or a TZID
 * without its VTIMEZONE — the host's wall clock, as toInstant reads those.
 */
function timeLike(instant, property, value = property.getFirstValue()) {
  const date = new Date(instant);
  if (value.isDate) {
    return new ICAL.Time({ year: date.getUTCFullYear(), month: date.getUTCMonth() + 1, day: date.getUTCDate(), isDate: true });
  }
  const frame = frameOf(property);
  if (frame === 'utc') return ICAL.Time.fromJSDate(date, true);
  const zone = documentZone(property);
  if (zone) return ICAL.Time.fromJSDate(date, true).convertToZone(zone);
  return new ICAL.Time({
    year: date.getFullYear(), month: date.getMonth() + 1, day: date.getDate(),
    hour: date.getHours(), minute: date.getMinutes(), second: date.getSeconds(),
  });
}

/**
 * The occurrence with recurrence id `id`, after its overrides: an exact
 * override if there is one, else the latest valid THISANDFUTURE override at
 * or before it, else the series itself. `futures` are the THISANDFUTURE
 * overrides that are occurrences (see validate), sorted.
 *
 * A THISANDFUTURE override moves later occurrences by its own move, read as
 * wall-clock time in its DTSTART's frame (so 10:00 -> 11:00 stays 11:00
 * across a DST change), and gives them its duration and properties.
 *
 * @returns {{recurrenceId: ICAL.Time, startDate: ICAL.Time, endDate: ICAL.Time, item: ICAL.Event}}
 */
function occurrenceAt(series, id, futures) {
  const { event } = series;
  const details = event.getOccurrenceDetails(id);
  if (details.item !== event || futures.length === 0) return details;

  const at = toInstant(id);
  let future = null;
  for (const candidate of futures) {
    if (candidate.at > at) break;
    future = candidate;
  }
  if (!future) return details;

  const exception = future.exception;
  const startProperty = exception.component.getFirstProperty('dtstart');
  if (!startProperty) return details;
  const move = exception.startDate.subtractDate(timeLike(future.at, startProperty));
  const startDate = timeLike(at, startProperty);
  startDate.addDuration(move);
  const endDate = startDate.clone();
  endDate.addDuration(exception.duration);
  return { recurrenceId: id, startDate, endDate, item: exception };
}

/** The key ical.js finds an exact override of `id` under, if any */
function exceptionKey(event, id) {
  const local = id.toString();
  if (local in event.exceptions) return local;
  const utc = id.convertToZone(ICAL.Timezone.utcTimezone).toString();
  return utc in event.exceptions ? utc : null;
}

/**
 * The occurrences of a recurring series that touch `range` and that `filter`
 * takes, each as it now stands (occurrenceAt).
 *
 * Without walking the whole series:
 *
 *  - Overrides with their own RECURRENCE-ID are a finite list, each with its
 *    own time. Those that touch the range are collected first, from anywhere
 *    in the series — that is how one moved in from years away is found.
 *  - Whether they, and any THISANDFUTURE overrides, are occurrences at all
 *    is checked in ONE walk over their sorted RECURRENCE-IDs (validate),
 *    which restarts near each id where the rule allows it (shiftPlan).
 *  - Every other occurrence sits at its recurrence id, moved at most by a
 *    valid THISANDFUTURE override and lasting at most the longest duration
 *    in the series. So only the recurrence ids in the range, widened by that
 *    move and duration, are walked — starting just before it where the rule
 *    allows (shiftPlan), else at DTSTART.
 *
 * @param {ReturnType<typeof relateSeries>} series
 * @param {{start: number, end: number}} range - ms
 * @param {Object} [options]
 * @param {((occurrence: Object) => boolean)|null} [options.filter] - beyond
 *   touching the range (a search, blocking time)
 * @param {boolean} [options.first] - only the earliest is wanted: the walk
 *   stops once no later recurrence id can start before it
 * @returns {{occurrences: Object[], truncated: boolean}} sorted by start,
 *   then recurrence id; truncated when a walk hit the iteration cap, so an
 *   occurrence may be missing
 */
export function seriesOccurrences(series, range, { filter = null, first = false } = {}) {
  const accept = (occurrence) => {
    const { start, end } = spanOf(occurrence);
    return touchesRange(start, end, range) && (!filter || filter(occurrence));
  };

  const overrides = overridesInRange(series, accept);
  const checked = validate(series, [...overrides, ...series.futures]);
  const futures = series.futures.filter((f) => checked.ids.has(f.key));
  const found = overrides
    .filter((o) => checked.ids.has(o.key))
    .map((o) => occurrenceAt(series, checked.ids.get(o.key), futures));

  const walked = walkRange(series, range, futures, accept, first ? earliest(found) : null);
  found.push(...walked.found);
  const truncated = checked.truncated || walked.truncated;
  if (truncated) {
    console.error(`Recurrence expansion gave up after ${MAX_RECURRENCE_ITERATIONS} occurrences`);
  }
  found.sort(byStart);
  return { occurrences: first ? found.slice(0, 1) : found, truncated };
}

/** The exact overrides whose own time `accept` takes: {key, at} */
function overridesInRange({ event }, accept) {
  return Object.entries(event.exceptions)
    .filter(([, exception]) => accept(event.getOccurrenceDetails(exception.recurrenceId)))
    .map(([key, exception]) => ({ key, at: toInstant(exception.recurrenceId) }));
}

function earliest(occurrences) {
  return Math.min(Infinity, ...occurrences.map((o) => spanOf(o).start));
}

/**
 * Walk the recurrence ids that can still yield an occurrence touching the
 * range, skipping exact overrides (judged by overridesInRange). With
 * `best` (first mode), stop once a later id cannot start before it.
 */
function walkRange(series, range, futures, accept, best) {
  const { event } = series;
  const { lead, trail, minMove } = reach(series, futures);
  const walk = walkFrom(series, range.start - lead);
  const to = range.end + trail;
  const found = [];
  let bound = best ?? Infinity;
  for (let id = walk.next(); id; id = walk.next()) {
    const at = toInstant(id);
    if (at > to) return { found, truncated: false };
    if (best !== null && at + minMove - ZONE_SLACK_MS > bound) return { found, truncated: false };
    if (exceptionKey(event, id)) continue;
    const occurrence = occurrenceAt(series, id, futures);
    if (accept(occurrence)) {
      found.push(occurrence);
      bound = Math.min(bound, spanOf(occurrence).start);
    }
  }
  return { found, truncated: walk.truncated() };
}

/**
 * How far an occurrence can sit from its recurrence id, in ms: `lead` back
 * (it may start before its id and run on into the range), `trail` forward,
 * and the most negative move a valid THISANDFUTURE override applies.
 */
function reach({ event }, futures) {
  const moves = [0];
  const durations = [durationOf(event)];
  for (const { exception, at } of futures) {
    moves.push(toInstant(exception.startDate) - at);
    durations.push(durationOf(exception));
  }
  const minMove = Math.min(...moves);
  return {
    lead: Math.max(...moves) + Math.max(0, ...durations) + ZONE_SLACK_MS,
    trail: -minMove + ZONE_SLACK_MS,
    minMove,
  };
}

function durationOf(event) {
  try {
    const ms = event.duration.toSeconds() * 1000;
    return Number.isFinite(ms) ? ms : 0;
  } catch {
    return 0;
  }
}

/**
 * Which of the given overrides are occurrences of the series — does the
 * rule, less its EXDATEs, yield their RECURRENCE-ID? One walk over the ids
 * in order; where the rule can be shifted (shiftPlan) it restarts just
 * before each id that lies ahead of it, else it runs on from DTSTART.
 *
 * @param {Object[]} targets - {key, at}
 * @returns {{ids: Map<string, ICAL.Time>, truncated: boolean}} each valid
 *   key with its id as the rule yields it
 */
function validate(series, targets) {
  const ids = new Map();
  const pending = [...new Map(targets.map((t) => [t.key, t])).values()].sort((a, b) => a.at - b.at);
  if (pending.length === 0) return { ids, truncated: false };

  const keys = new Set(pending.map((t) => t.key));
  let walk = null;
  let position = -Infinity;
  for (let i = 0; i < pending.length;) {
    const target = pending[i];
    if (target.at + ZONE_SLACK_MS < position) {
      i++;
      continue;
    }
    // restart near the next id when that is cheaper than walking on to it
    const ahead = target.at - ZONE_SLACK_MS - position;
    if (!walk || (series.plan && ahead > (series.plan.stepDays + 3) * DAY_MS)) {
      walk = walkFrom(series, target.at - ZONE_SLACK_MS);
    }
    const id = walk.next();
    // the end of the series: no later id is an occurrence either
    if (!id) return { ids, truncated: walk.truncated() };
    position = toInstant(id);
    const key = exceptionKey(series.event, id);
    if (key && keys.has(key)) ids.set(key, id);
  }
  return { ids, truncated: false };
}

/**
 * The recurrence ids of a series in order, from `from` (ms) on, starting
 * just before it where shiftPlan allows, else at DTSTART. next() returns null at the end of
 * the series or at the iteration cap; truncated() tells which.
 */
function walkFrom(series, from) {
  const { event, plan } = series;
  let dtstart = event.startDate;
  if (plan) {
    const daysToFrom = Math.floor((from - toInstant(dtstart)) / DAY_MS);
    const steps = Math.floor((daysToFrom - plan.stepDays - 2) / plan.stepDays);
    if (steps > 0) {
      dtstart = dtstart.clone();
      dtstart.adjust(steps * plan.stepDays, 0, 0, 0);
    }
  }
  const expansion = new ICAL.RecurExpansion({ component: event.component, dtstart });
  let steps = 0;
  let truncated = false;
  return {
    next() {
      for (;;) {
        if (steps++ >= MAX_RECURRENCE_ITERATIONS) {
          truncated = true;
          return null;
        }
        const id = expansion.next();
        if (!id || (plan?.last && id.compare(plan.last) > 0)) return null;
        // nothing before `from` is asked for — and a shifted walk yields its
        // own start too, occurrence or not
        if (toInstant(id) < from) continue;
        return id;
      }
    },
    truncated: () => truncated,
  };
}

// Rule parts that keep a series periodic in its INTERVAL: the candidates are
// the same in every period, so the expansion can start a whole number of
// periods later without changing which occurrences it yields.
const PERIODIC_PARTS = new Set(['BYDAY', 'BYMONTH', 'BYHOUR', 'BYMINUTE', 'BYSECOND', 'WKST']);
const UNIT_SECONDS = { SECONDLY: 1, MINUTELY: 60, HOURLY: 3600, DAILY: 86400, WEEKLY: 604800 };

/**
 * Whether, and in which steps, a walk may start later than DTSTART.
 *
 * Walking from DTSTART costs one step per occurrence since the series began:
 * a daily series from 2020 takes ~2400 steps to reach October 2026, an
 * hourly one from last year runs into the cap. For a SECONDLY to WEEKLY rule
 * restricted by BYDAY/BYMONTH at most, the candidates repeat every period,
 * and ical.js steps them on the wall clock, so a start moved by a whole
 * number of days that is also a whole number of periods (`stepDays`) yields
 * the same occurrences from there on. EXDATEs and overrides are absolute and
 * still apply. With COUNT, only a rule without BY parts qualifies: its last
 * occurrence (`last`) is then DTSTART plus COUNT-1 periods, and the walk
 * stops there. Anything else — RDATE, several RRULEs, MONTHLY, YEARLY, other
 * BY parts — is walked from DTSTART; monthly and yearly series have few
 * occurrences.
 *
 * @returns {{stepDays: number, last: ICAL.Time|null}|null}
 */
function shiftPlan(event) {
  const component = event.component;
  const rules = component.getAllProperties('rrule');
  if (rules.length !== 1 || component.hasProperty('rdate')) return null;
  const rule = rules[0].getFirstValue();
  const unit = UNIT_SECONDS[rule.freq];
  if (!unit) return null;
  const parts = Object.keys(rule.parts ?? {});
  if (parts.some((part) => !PERIODIC_PARTS.has(part))) return null;

  const period = (rule.interval || 1) * unit;
  let last = null;
  if (rule.count) {
    if (parts.some((part) => part !== 'WKST')) return null;
    last = event.startDate.clone();
    const span = (rule.count - 1) * period;
    if (unit >= 86400) last.adjust(span / 86400, 0, 0, 0);
    else last.adjust(0, 0, 0, span);
  }
  return { stepDays: period / gcd(period, 86400), last };
}

function gcd(a, b) {
  return b === 0 ? a : gcd(b, a % b);
}

function byStart(a, b) {
  return spanOf(a).start - spanOf(b).start || toInstant(a.recurrenceId) - toInstant(b.recurrenceId);
}
